### ISSUE TITLE
Question - relation to Doist plugin

### ISSUE THREAD

**Issue by emartynov** [j-roskopf/KotlinWarningBaselineGenerator#3]
It's super lovely to see it!

I see mention of the Doist plugin - how is this project related? Looks like not a fork.

Kind Regards,
Eugen

**Comment by j-roskopf** [comment]
Hey! 

The project is spiritually similar to the Doist one for sure, but not a fork as you mentioned. There were several issues with the Doist implementation that I needed changed for my own needs and it appeared the project had not been updated in a few years / issues hadn't been addressed, so I made those changes and published this one. I'd be happy to upstream my changes to reduce confusion! I sent out an initial feeler to the Doist team, but haven't heard back yet. 

A few of the issues I ran into with the Doist one:

1. relying on `clean` task to run before baseline. I understand why it was done, but it would be a bit burdensome for my use cases to always run clean. Instead, this version disables incremental compilation / up to date checks for kotlin compile tasks when running the write / check baseline tasks

2. I couldn't get it to work for my personal projects for the reason stated in this issue - https://github.com/Doist/kotlin-warning-baseline/issues/9

3. deprecated gradle APIs - the Doist one relies on deprecated task completion / output listener gradle APIs. this version has been updated to use no deprecated gradle APIs as of 8.9

**Comment by emartynov** [comment]
Thanks for the explanations! 

And we have a legacy project, and I will play with the plugin for a while.

**Comment by j-roskopf** [comment]
of course! please let me know if ya run into any issues. Happy to address them!

one last thing with the Doist plugin is I wanted to avoid relying on `afterEvaluate` in the plugin - https://github.com/Doist/kotlin-warning-baseline/blob/00f685d7b6d156bf50106a722bc5880340e12630/src/main/kotlin/com/doist/gradle/KotlinWarningBaselinePlugin.kt#L23

https://blog.mbonnin.net/my-life-after-afterevaluate
https://youtrack.jetbrains.com/issue/IDEA-343338/Please-avoid-using-afterEvaluate-in-Gradle-logic
